source 'https://rubygems.org'

gem 'rails', '4.1.1'
gem 'pg'
gem 'uglifier'
gem 'jquery-rails'
gem 'twitter-bootstrap-rails'
gem 'bcrypt'
gem 'factory_girl'
gem 'kaminari'
gem 'friendly_id'
gem 'devise'
gem 'therubyracer'
gem 'nested_form'
gem 'paper_trail', '~> 3.0.1'
gem 'pundit' # authorization
gem 'sunspot_rails'
gem 'sunspot_solr' # optional pre-packaged Solr distribution for use in development
gem 'unicorn'
gem 'omniauth-twitter'
gem 'figaro'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'quiet_assets'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'capybara'
  gem 'factory_girl_rails'
  gem 'launchy'
  gem 'faker'
  gem 'dotenv-rails'
  gem 'rerun'
  gem 'pry'
  gem 'pry-nav'
end

group :test do
  gem 'minitest'
  gem 'shoulda-matchers'
  gem 'shoulda-callback-matchers'
  gem 'database_cleaner'
end


# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

